def get_users():
    return [
        {
            "id": 1,
            "firstName": "John",
            "lastName": "Doe",
            "age": 30,
            "gender": "male",
            "email": "john@doe.com",
            "phone": "123-456-7890",
        },
        {
            "id": 2,
            "firstName": "Jane",
            "lastName": "Doe",
            "age": 30,
            "gender": "female",
            "email": "jane@doe.com",
            "phone": "123-456-7891",
        },
        {
            "id": 3,
            "firstName": "Alice",
            "lastName": "Doe",
            "age": 28,
            "gender": "female",
            "email": "alice@doe.com",
            "phone": "123-456-7892",
        },
        {
            "id": 4,
            "firstName": "Bob",
            "lastName": "Doe",
            "age": 32,
            "gender": "male",
            "email": "bob@doe.com",
            "phone": "123-456-7893",
        },
        {
            "id": 5,
            "firstName": "Charlie",
            "lastName": "Doe",
            "age": 25,
            "gender": "male",
            "email": "charlie@doe.com",
            "phone": "123-456-7894",
        },
        {
            "id": 6,
            "firstName": "Emily",
            "lastName": "Smith",
            "age": 27,
            "gender": "female",
            "email": "emily@smith.com",
            "phone": "123-456-7895",
        },
        {
            "id": 7,
            "firstName": "Daniel",
            "lastName": "Smith",
            "age": 31,
            "gender": "male",
            "email": "daniel@smith.com",
            "phone": "123-456-7896",
        },
        {
            "id": 8,
            "firstName": "Olivia",
            "lastName": "Brown",
            "age": 29,
            "gender": "female",
            "email": "olivia@brown.com",
            "phone": "123-456-7897",
        },
        {
            "id": 9,
            "firstName": "Henry",
            "lastName": "Brown",
            "age": 35,
            "gender": "male",
            "email": "henry@brown.com",
            "phone": "123-456-7898",
        },
        {
            "id": 10,
            "firstName": "Liam",
            "lastName": "Johnson",
            "age": 26,
            "gender": "male",
            "email": "liam@johnson.com",
            "phone": "123-456-7899",
        },
        {
            "id": 11,
            "firstName": "Emma",
            "lastName": "Johnson",
            "age": 34,
            "gender": "female",
            "email": "emma@johnson.com",
            "phone": "123-456-7800",
        },
        {
            "id": 12,
            "firstName": "Michael",
            "lastName": "Williams",
            "age": 28,
            "gender": "male",
            "email": "michael@williams.com",
            "phone": "123-456-7801",
        },
        {
            "id": 13,
            "firstName": "Sophia",
            "lastName": "Williams",
            "age": 30,
            "gender": "female",
            "email": "sophia@williams.com",
            "phone": "123-456-7802",
        },
        {
            "id": 14,
            "firstName": "David",
            "lastName": "Jones",
            "age": 32,
            "gender": "male",
            "email": "david@jones.com",
            "phone": "123-456-7803",
        },
        {
            "id": 15,
            "firstName": "Isabella",
            "lastName": "Jones",
            "age": 27,
            "gender": "female",
            "email": "isabella@jones.com",
            "phone": "123-456-7804",
        },
        {
            "id": 16,
            "firstName": "James",
            "lastName": "Miller",
            "age": 33,
            "gender": "male",
            "email": "james@miller.com",
            "phone": "123-456-7805",
        },
        {
            "id": 17,
            "firstName": "Mia",
            "lastName": "Miller",
            "age": 29,
            "gender": "female",
            "email": "mia@miller.com",
            "phone": "123-456-7806",
        },
        {
            "id": 18,
            "firstName": "Benjamin",
            "lastName": "Davis",
            "age": 35,
            "gender": "male",
            "email": "benjamin@davis.com",
            "phone": "123-456-7807",
        },
        {
            "id": 19,
            "firstName": "Charlotte",
            "lastName": "Davis",
            "age": 31,
            "gender": "female",
            "email": "charlotte@davis.com",
            "phone": "123-456-7808",
        },
        {
            "id": 20,
            "firstName": "Lucas",
            "lastName": "Garcia",
            "age": 28,
            "gender": "male",
            "email": "lucas@garcia.com",
            "phone": "123-456-7809",
        },
        {
            "id": 21,
            "firstName": "Amelia",
            "lastName": "Garcia",
            "age": 26,
            "gender": "female",
            "email": "amelia@garcia.com",
            "phone": "123-456-7810",
        },
        {
            "id": 22,
            "firstName": "Matthew",
            "lastName": "Martinez",
            "age": 34,
            "gender": "male",
            "email": "matthew@martinez.com",
            "phone": "123-456-7811",
        },
        {
            "id": 23,
            "firstName": "Harper",
            "lastName": "Martinez",
            "age": 29,
            "gender": "female",
            "email": "harper@martinez.com",
            "phone": "123-456-7812",
        },
        {
            "id": 24,
            "firstName": "Sebastian",
            "lastName": "Clark",
            "age": 30,
            "gender": "male",
            "email": "sebastian@clark.com",
            "phone": "123-456-7813",
        },
        {
            "id": 25,
            "firstName": "Evelyn",
            "lastName": "Clark",
            "age": 32,
            "gender": "female",
            "email": "evelyn@clark.com",
            "phone": "123-456-7814",
        },
    ]


def get_user_by_id(user_id):
    users = get_users()
    for user in users:
        if user["id"] == user_id:
            return user
    return None


def update_user(user_id, user_data):
    user = get_user_by_id(user_id)
    if not user:
        return None

    for key, value in user_data.items():
        if value is not None:
            user[key] = value
    return user
